name: TEST---

on:
  workflow_dispatch:
    inputs:
      docker_images:
        description: 'Comma-separated list of Docker images to pull'
        required: true
        default: 'alpine:latest,ubuntu:latest'  # 设置默认的 Docker 镜像列表

jobs:
  pull_and_package:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        platform: [amd64, arm64]  # 在这里定义你希望支持的平台列表

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Pull Docker Images
      run: |
        images="${{ github.event.inputs.docker_images }}"
        IFS=',' read -r -a image_array <<< "$images"
        for image in "${image_array[@]}"; do
          for platform in ${{ matrix.platform }}; do
            docker pull "${image}-${platform}"
            docker save "${image}-${platform}" -o "${image//\//_}-${platform}.tar"
          done
        done

    - name: Compress the TAR files
      run: tar -czf images.tar.gz *.tar

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: docker-images-tar
        path: images.tar.gz
