name: Docker Pull and Package

on:
  workflow_dispatch:
    inputs:
      docker_images:
        description: 'Comma-separated list of Docker images to pull'
        required: true
        default: 'alpine:latest,ubuntu:latest'  # 你可以设置一个默认值

jobs:
  pull_and_package:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Pull Docker Images
      run: |
        images="${{ github.event.inputs.docker_images }}"
        IFS=',' read -r -a image_array <<< "$images"
        for image in "${image_array[@]}"; do
          docker pull "$image"
          docker save "$image" -o "${image//\//_}.tar"
        done

    - name: Compress the TAR files
      run: tar -czf images.tar.gz *.tar

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: docker-images-tar
        path: images.tar.gz
